---
title: Econometría I
subtitle: "Reto 05"
author:
  name: Carlos A. Yanes Guerra
  affiliation: Universidad del Norte | Departamento de Economía
# date: "`r format(Sys.time(), '%d %B %Y')`" ## Or "Lecture no."
output: 
  html_document:
    keep_md: false
    theme: journal
    highlight: haddock
    # code_folding: show
    toc: yes
    toc_depth: 4
    toc_float: yes
    css: css/preamble.css ## For multi-col environments
  pdf_document:
    latex_engine: xelatex
    keep_tex: false ## Change to true if want keep intermediate .tex file
    toc: true
    toc_depth: 3
    dev: cairo_pdf
    # fig_width: 7 ## Optional: Set default PDF figure width
    # fig_height: 6 ## Optional: Set default PDF figure height
    extra_dependencies: ['booktabs', 'threeparttable', 'float'] # "longtable"
    includes:
      in_header: tex/preamble.tex ## For multi-col environments
    pandoc_args:
        --template=tex/mytemplate.tex ## For affiliation field. See: https://bit.ly/2T191uZ
always_allow_html: true
urlcolor: blue
mainfont: cochineal
sansfont: Fira Sans
monofont: Fira Code ## Although, see: https://tex.stackexchange.com/q/294362
## Automatically knit to both formats:
knit: (function(inputFile, encoding) {
 rmarkdown::render(inputFile, encoding = encoding, 
 output_format = 'all') 
 })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, dpi=300, fig.align = "center")
```

## Antes de empezar
Llegamos al reto de comprobacion de violación de supuestos de MCO (Heterocedasticidad y Autocorrelación. Recuerde que los retos son para desarrollarlos en clases en el tiempo sugerido por el profesor **1H:30 Min**. Trate con su grupo de trabajo (2 personas) hacer uso de la guía general del curso, buscando eso que  -*tenga un toque único*- y no porque se lo da la IA.

## Objetivo
Medir los problemas de Heterocedasticidad y Autocorrelación. Ademas de ello, si hay presencia de alguno de ellos, intentar resolverlo con las técnicas propuestas en clase.

### Parte 1 Heterocedasticidad

Aunque un vino es considerado como un bien de consumo, los vinos de antaño (viejos) pueden considerarse un **bien de inversión**, -*dadas sus características claro esta*-. En concreto, se tienen de datos sobre los precios de subasta de miles de de vinos tintos tipo de Burdeos desde el año de 1952 a 1980. Estos vinos, se almacenan durante un periodo de tiempo considerable antes de ser consumidos, lo que conlleva a un aumento del precio dado el costo de almacenamiento. Esto supone un costo de oportunidad ante la posibilidad de invertir en otras alternativas. La información con que se cuenta esta en el archivo **vinos.csv** y la etiqueta de variables es *lnpr* para el logaritmo del precio del vino; *lluvinv* es la cantidad de lluvia en el invierno que cae antes de la cosecha; *tempmedia* es la temperatura promedio en grados celsius; *lluveco* es la cantidad de lluvia durante la maduración de la uva) y la *edad* es el número de años transcurridos desde la cosecha.

**1.** Realice una regresión múltiple del logaritmo del precio sobre las variables de edad, lluvinv, lluvecos, tempmedia. ¿Qué conclusión saca para esta parte?

**2.** Piense que por un momento le piden que declare una variable *ficticia* donde toma el valor de uno (1), si el vino tiene mas de 16 años de añejo. Este grupo es mas rentable que el otro si solo miramos esta variable para el análisis de la rentabilidad del vino. *Comente*.

**3.** Probemos la heterocedasticidad del modelo. Primero grafique el `residuo de su modelo` con las variables explicativas del inciso **1**, luego el residuo vs el `y predicho`. Qué observa? hay algun problema?. Aplique ahora el siguiente test:

```r
# install.package("lmtest")
library(lmtest)
# Para Breusch-Pagan
bptest(reg)
```

**3a.** Qué encuentra?. En caso tal su modelo tenga heterocedasticidad. corrija de la siguiente forma:

```r
# Corrección errores robustos de White
regwhite<-coeftest(reg, hccm)
regwhite
```

**3b.** ¿Qué diferencias encuentra con la estimación original?

## Datos de trabajo Parte 2
Sea la siguiente tabla con información de una empresa (ambas variables estan en millones de pesos colombianos).

\begin{table}[h!]
\begin{tabular}{|l|l|l|}
\hline
\textit{\textbf{i}} & \textit{\textbf{Ventas}} & \textit{\textbf{Publicidad}} \\ \hline
1 & 290.2 & 19  \\ \hline
2 & 264.2 & 20.2 \\ \hline
3 & 244.6 & 18.7 \\ \hline
4 & 288.8 & 23.2 \\ \hline
5 & 223 & 20.6 \\ \hline
6 & 223 & 19  \\ \hline
7 & 265.4 & 22.4 \\ \hline
8 & 253.8 & 18 \\ \hline
9 & 302 & 22 \\ \hline
10 & 304 & 22 \\ \hline
11 & 305 & 24 \\ \hline
12 & 221 & 19 \\ \hline
13 & 345 & 28.2 \\ \hline
14 & 305 & 22.5 \\ \hline
15 & 346 & 28 \\ \hline
\end{tabular}%

\end{table}

### Parte 2 Autocorrelación

Una empresa de licores quiere conocer como de cierta manera la inversión en millones de pesos en \textcolor{blue}{publicidad} en cada uno de los 10 puntos que tiene en la ciudad, le retorna en mejores ingresos para su negocio. El área de analítica ha contratado a un estudiante de la Universidad del Norte para intentar resolver el problema y dar respuesta a varios items que ha propuesto la organización.

\begin{center}
    \textbf{Deben invertir en mas publicidad? Si ellos deciden invertir un monto de 15 millones de pesos, cuanto mas o menos eso incrementa sus ventas con respecto al promedio de ventas?}
\end{center}

**1.** Haga uno a uno cada paso que se establece a continuación:

\begin{itemize}
\item Ejecute una primera regresión (1). *Muestre los resultados, incluyendo valores predichos y residuales*. 
\item Ahora haga lo mismo una segunda regresión (2) pero añadiendo el cuadrado de la variable explicativa.
\item Haga ahora una tercera regresión (3), pero añade ahora el cubo de la variable explicativa.
\item ¿Qué "modelo" de regresión está estimando? Específicamente, ¿Qué tipo de relación supone que existe entre qué variables? ¿qué diferencias hay entre los modelos?. 
\item Específicamente, ¿qué le dicen las ventas observadas, las ventas predichas y las columnas de los residuales? ¿tiene algo que ver cómo se calculan?
\end{itemize}

**2.** Estime la prueba de durbin watson con el primer modelo o regresión (1)

**3.** Establezca la corrección vía dos estapas y diga que ocurre. No solo muetsre la salida. Interprete. 

```r
# Corrección 
cochrane.orcutt(reg)
```
**4.** Responda a la pregunta central de esto. Debe invertir los 15 millones de pesos en públicidad?



