---
title: Econometría I
subtitle: "Reto 04"
author:
  name: Carlos A. Yanes Guerra
  affiliation: Universidad del Norte | Departamento de Economía
# date: "`r format(Sys.time(), '%d %B %Y')`" ## Or "Lecture no."
output: 
  html_document:
    keep_md: false
    theme: journal
    highlight: haddock
    # code_folding: show
    toc: yes
    toc_depth: 4
    toc_float: yes
    css: css/preamble.css ## For multi-col environments
  pdf_document:
    latex_engine: xelatex
    keep_tex: false ## Change to true if want keep intermediate .tex file
    toc: true
    toc_depth: 3
    dev: cairo_pdf
    # fig_width: 7 ## Optional: Set default PDF figure width
    # fig_height: 6 ## Optional: Set default PDF figure height
    extra_dependencies: ['booktabs', 'threeparttable', 'float'] # "longtable"
    includes:
      in_header: tex/preamble.tex ## For multi-col environments
    pandoc_args:
        --template=tex/mytemplate.tex ## For affiliation field. See: https://bit.ly/2T191uZ
always_allow_html: true
urlcolor: blue
mainfont: cochineal
sansfont: Fira Sans
monofont: Fira Code ## Although, see: https://tex.stackexchange.com/q/294362
## Automatically knit to both formats:
knit: (function(inputFile, encoding) {
 rmarkdown::render(inputFile, encoding = encoding, 
 output_format = 'all') 
 })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, dpi=300, fig.align = "center")
```

## Antes de empezar
Llegamos al reto de variables cualitativas. Recuerde que los retos son para desarrollarlos en clases en el tiempo sugerido por el profesor **1H:30 Min**. Trate con su grupo de trabajo (2 personas) hacer uso de la guía general del curso, buscando eso que  -*tenga un toque único*- y no porque se lo da la IA.

## Objetivo
Comenzar a trabajar con modelos que incluyen variables cualitativas

### Datos de trabajo
Sea la siguiente tabla con información:

\begin{table}[!ht]
    \centering
    \begin{tabular}{|l|l|l|l|}
    \hline
        Ingreso (COP) & Secundaria (dummy) & Universidad (dummy) & Género (dummy) \\ \hline
        650,000 & 1 & 0 & 0 \\ \hline
        800,000 & 1 & 0 & 1 \\ \hline
        1,200,000 & 0 & 1 & 1 \\ \hline
        900,000 & 1 & 0 & 1 \\ \hline
        700,000 & 1 & 0 & 0 \\ \hline
        1,500,000 & 0 & 1 & 1 \\ \hline
        1,300,000 & 0 & 1 & 0 \\ \hline
        850,000 & 1 & 0 & 0 \\ \hline
        950,000 & 1 & 0 & 1 \\ \hline
        1,000,000 & 1 & 0 & 0 \\ \hline
        1,100,000 & 0 & 1 & 1 \\ \hline
        600,000 & 1 & 0 & 0 \\ \hline
        750,000 & 1 & 0 & 1 \\ \hline
        1,250,000 & 0 & 1 & 1 \\ \hline
        1,400,000 & 0 & 1 & 0 \\ \hline
        700,000 & 1 & 0 & 1 \\ \hline
        1,050,000 & 0 & 1 & 1 \\ \hline
        980,000 & 1 & 0 & 0 \\ \hline
        1,100,000 & 0 & 1 & 1 \\ \hline
        900,000 & 1 & 0 & 1 \\ \hline
    \end{tabular}
\end{table}

\newpage

## Preguntas del Reto!

**1.** Con las variables ( _Ingreso_, _genero_ y _Universidad_) establezca un modelo de regresión múltiple e interprete los resultados del modelo.

**2.** ¿Existe una diferencia significativa en los ingresos entre hombres y mujeres, controlando por el nivel educativo?

**3.** Por un momento digamos que queremos medir el haber realizado una capacitación y que tan solo las 10 primeras observaciones lo hicieron. Cosntruya una dummy que permita diferenciar entre los que la hicieron y los que no. Luego de eso haga una interaccion con cada variable anterior y nuevamente mire que hace los modelos e interprete el resultado. **Pista**: puede usar `modelo<-lm(y~capacitacion*(x1+x2), data = base)`

**4.** Digamos ahora que queremos aprender de las variables de rango. Para ello vamos a crear lo siguiente:

```r
datos$prom<-c(3.1,3.6,3.8,4.1,4.3,3.4,3.5,3.7,3.8,3.9,4.1,4.6,5.0,
4.8,4.5,4.3,4.1,3.6,3.2,3.2)

# Definir cortes de la variable
corte<-c(2.0,2.5,3.0,3.5,4.0,4.5,5.0)

# Creamos una variable ranqueada
datos$ranking<-cut(datos$prom, corte)

# Una tabla de lo que hace
table(datos$ranking)
```

Teniendo eso, va a tener una variable rankeada. Haga a continuación un modelo con esta variable sin incluir interacciones solo con las variables iniciales y ahora vuelva e interprete. Qué encuentra?

**5.** Qué ocurre finalmente con las notas de las personas, es una variable que para este caso si es fundamental para la definición del salario de una persona?